SUBSISTEMAS = ["SE", "S", "NE", "N"]
REES = ["SUDESTE", "SUL", "NORDESTE", "NORTE",
        "ITAIPU", "MADEIRA", "TPIRES", "BMONTE",
        "MAN-AP", "PARANA", "IGUACU", "PRNPANEMA"]
MAX_SEMANAS_PRE = 10
