name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10.11", "3.11.3"]
    steps:
    - uses: actions/checkout@v3
    - name: Configura o Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Instala os requisitos do módulo
      run: |
        pip install -r dev-requirements.txt
    - name: Executa os testes do pacote
      run: |
        pytest --cov-report=xml --cov=idecomp tests/
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        files: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-idecomp
        fail_ci_if_error: true 
        verbose: true 
    - name: Veriricações de qualidade de código - tipagem estática
      run: |
        mypy ./idecomp
    - name: Verificações de qualidade de código - linter PEP8
      run: |
        pylama --ignore E203 ./idecomp
